### ISSUE TITLE
无法从末地传送到主世界

### ISSUE THREAD

**Issue by zhenaiwork** [2No2Name/worldthreader#6]
在向末地到主世界的传送门放入一个实体就会导致服务器崩溃

```
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2023-12-12 21:33:15
Description: Colliding entity with block

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2338.method_10263()" because "pos" is null
	at net.minecraft.class_1937.method_8320(class_1937.java:7051)
	at net.minecraft.class_1297.handler$cag000$worldthreader$moveToWorld(class_1297.java:12390)
	at net.minecraft.class_1297.method_5731(class_1297.java:2702)
	at net.minecraft.class_1542.method_5731(class_1542.java:391)
	at net.minecraft.class_2334.method_9548(class_2334.java:47)
	at net.minecraft.class_4970$class_4971.method_26178(class_4970.java:1121)
	at net.minecraft.class_1297.method_5852(class_1297.java:1137)
	at net.minecraft.class_1297.method_36974(class_1297.java:851)
	at net.minecraft.class_1297.method_5784(class_1297.java:799)
	at net.minecraft.class_1542.method_5773(class_1542.java:136)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at _2no2name.worldthreader.common.ServerWorldTicking.tickThreaded(ServerWorldTicking.java:61)
	at _2no2name.worldthreader.common.ServerWorldTicking.runWorldThread(ServerWorldTicking.java:34)
	at _2no2name.worldthreader.common.thread.WorldThreadingManager.lambda$new$0(WorldThreadingManager.java:45)
	at java.base/java.lang.Thread.run(Thread.java:1583)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_1937.method_8320(class_1937.java:7051)
	at net.minecraft.class_1297.handler$cag000$worldthreader$moveToWorld(class_1297.java:12390)
	at net.minecraft.class_1297.method_5731(class_1297.java:2702)
	at net.minecraft.class_1542.method_5731(class_1542.java:391)
	at net.minecraft.class_2334.method_9548(class_2334.java:47)
	at net.minecraft.class_4970$class_4971.method_26178(class_4970.java:1121)
	at net.minecraft.class_1297.method_5852(class_1297.java:1137)
	at net.minecraft.class_1297.method_36974(class_1297.java:851)
	at net.minecraft.class_1297.method_5784(class_1297.java:799)
	at net.minecraft.class_1542.method_5773(class_1542.java:136)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)

-- Block being collided with --
Details:
	Block: Block{minecraft:end_portal}
	Block location: World: (1,61,-1), Section: (at 1,13,15 in 0,3,-1; chunk contains blocks 0,0,-16 to 15,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
Stacktrace:
	at net.minecraft.class_1297.method_5852(class_1297.java:1137)
	at net.minecraft.class_1297.method_36974(class_1297.java:851)
	at net.minecraft.class_1297.method_5784(class_1297.java:799)
	at net.minecraft.class_1542.method_5773(class_1542.java:136)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at _2no2name.worldthreader.common.ServerWorldTicking.tickThreaded(ServerWorldTicking.java:61)
	at _2no2name.worldthreader.common.ServerWorldTicking.runWorldThread(ServerWorldTicking.java:34)
	at _2no2name.worldthreader.common.thread.WorldThreadingManager.lambda$new$0(WorldThreadingManager.java:45)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- Entity being checked for collision --
Details:
	Entity Type: minecraft:item (net.minecraft.class_1542)
	Entity ID: 4793
	Entity Name: Torch
	Entity's Exact location: 1.13, 61.74, -0.30
	Entity's Block location: World: (1,61,-1), Section: (at 1,13,15 in 0,3,-1; chunk contains blocks 0,0,-16 to 15,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: -0.03, -0.34, -0.04
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1297.method_36974(class_1297.java:851)
	at net.minecraft.class_1297.method_5784(class_1297.java:799)
	at net.minecraft.class_1542.method_5773(class_1542.java:136)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at _2no2name.worldthreader.common.ServerWorldTicking.tickThreaded(ServerWorldTicking.java:61)
	at _2no2name.worldthreader.common.ServerWorldTicking.runWorldThread(ServerWorldTicking.java:34)
	at _2no2name.worldthreader.common.thread.WorldThreadingManager.lambda$new$0(WorldThreadingManager.java:45)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- Entity being ticked --
Details:
	Entity Type: minecraft:item (net.minecraft.class_1542)
	Entity ID: 4793
	Entity Name: Torch
	Entity's Exact location: 1.13, 61.74, -0.30
	Entity's Block location: World: (1,61,-1), Section: (at 1,13,15 in 0,3,-1; chunk contains blocks 0,0,-16 to 15,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: -0.03, -0.34, -0.04
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at _2no2name.worldthreader.common.ServerWorldTicking.tickThreaded(ServerWorldTicking.java:61)
	at _2no2name.worldthreader.common.ServerWorldTicking.runWorldThread(ServerWorldTicking.java:34)
	at _2no2name.worldthreader.common.thread.WorldThreadingManager.lambda$new$0(WorldThreadingManager.java:45)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- Affected level --
Details:
	All players: 1 total; [class_3222['zhenai_'/5, l='ServerLevel[world]', x=100.50, y=49.00, z=0.50]]
	Chunk stats: 2450
	Level dimension: minecraft:the_end
	Derived: true
	Level spawn location: World: (-144,73,-224), Section: (at 0,9,0 in -9,4,-14; chunk contains blocks -144,0,-224 to -129,255,-209), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 172882678 game time, 182517950 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 24136 (now: false), thunder time: 50551 (now: false)
	Known server brands: vanilla, fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at _2no2name.worldthreader.common.ServerWorldTicking.delegateCrash(ServerWorldTicking.java:88)
	at _2no2name.worldthreader.common.ServerWorldTicking.tickThreaded(ServerWorldTicking.java:63)
	at _2no2name.worldthreader.common.ServerWorldTicking.runWorldThread(ServerWorldTicking.java:34)
	at _2no2name.worldthreader.common.thread.WorldThreadingManager.lambda$new$0(WorldThreadingManager.java:45)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 6.2.16-060216-generic
	Java Version: 21, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 815793952 bytes (778 MiB) / 2097152000 bytes (2000 MiB) up to 8380219392 bytes (7992 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800X 8-Core Processor
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 5.08
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: GP107 [GeForce GTX 1050 Ti]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288.00
	Graphics card #0 deviceId: 0x1c82
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 18030.97
	Virtual memory used (MB): 9128.07
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 1064.97
	JVM Flags: 0 total; 
	Fabric Mods: 
		carpet: Carpet Mod 1.4.112+v230608
		carpet-extra: Carpet Extra 1.4.115
		carpet-sd-addition: SkyDynamic-Carpet-Addition 1.0.5
		fabric-api: Fabric API 0.86.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.62+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.2.0+6c31357e77
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.52+b3afc78b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.9+132c48c177
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.9+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.49+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.19+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.0+2e061fd477
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.34+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.28+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.0+cdf060b277
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabricloader: Fabric Loader 0.15.1
			mixinextras: MixinExtras 0.3.1
		gca: GugleCarpetAddition 2.7.0-1.20.1
		java: OpenJDK 64-Bit Server VM 21
		lithium: Lithium 0.11.2
		magiclib: MagicLib 0.7.346+e235d92-stable
			magiclib-1_20_1: MagicLib for 1.20.1 0.7.346+e235d92-stable
		minecraft: Minecraft 1.20.1
		pca-1_20_1: Plusls Carpet Addition 0.3.169+6510223-beta
		quickshulker: Quick Shulker 1.4.0-1.20
			kyrptconfig: Kyrpt Config 1.5.4-1.20
			shulkerutils: shulkerutils 1.0.4-1.19
		servercore: ServerCore 1.3.7+1.20.1
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			placeholder-api: Placeholder API 2.1.1+1.20
		servux: Servux 0.1.0
		smoothchunk: Smooth chunk save Mod 1.20.1-3.0
		starlight: Starlight 1.1.2+fabric.dbc156f
		syncmatica: Syncmatica 1.20.1-0.3.9
		worldthreader: DimensionalThreading 1.5.0
	Server Running: true
	Player Count: 2 / 114514; [class_3222['zhenai_'/5, l='ServerLevel[world]', x=100.50, y=49.00, z=0.50], class_3222['loukurlk'/2567, l='ServerLevel[world]', x=20.06, y=63.00, z=-1569.61]]
	Data Packs: vanilla, file/server.zip (incompatible), file/xklazy.zip (incompatible), fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by 2No2Name** [comment]
Seems to be fixed in latest version
